'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ranching_Game.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property coop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cow_N() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cow N", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cow_S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cow S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farmer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_E0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer E0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_E1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer E1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_E2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer E2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_E3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer E3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_E4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer E4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_E5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer E5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_E6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer E6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_E7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer E7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_N0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer N0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_N1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer N1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_N2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer N2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_N3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer N3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_N4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer N4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_N5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer N5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_N6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer N6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_N7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer N7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_S0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer S0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_S1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer S1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_S2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer S2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_S3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer S3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_S4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer S4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_S5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer S5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_S6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer S6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Farmer_S7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Farmer S7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farmer_W0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer W0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farmer_W1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer W1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farmer_W2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer W2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farmer_W3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer W3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farmer_W4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer W4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farmer_W5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer W5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farmer_W6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer W6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farmer_W7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer W7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Grass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property muuuh_n0000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("muuuh n0000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property muuuh_s0000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("muuuh s0000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
